@isset($request->type)
    @match($request->type)
        @case('register')       @do($memberController->register($request))
        @case('login')          @do($memberController->login($request))
        @case('reset_send')     @do($memberController->sendResetToken($request))
        @case('reset_user')     @do($memberController->sendForgottenUser($request))
        @case('new_password')   @do($memberController->setNewPassword($request))
        @case('update')         @do($memberController->update($request))
        @case('delete')         @do($memberController->delete($request))
        @case('create')         @do($memberController->create($request))
    @endmatch()
@endisset()
